spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cards-ms
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
